### PR TITLE
Added optional hint accept and content-type

### PR DESCRIPTION
**Pull request by ben-tsai**
Allow user to optional hint accept and content-type in resource definition.  

For example:

```
resource String POST "/CustomContentType" {
   String body

   accept application/xml, application/json  // some comment here
   content-type application/json, application/xml, text/plain;

   expected OK;
   exceptions {
       ResourceError INTERNAL_SERVER_ERROR;
       ResourceError BAD_REQUEST;
       ResourceError UNAUTHORIZED;
       ResourceError FORBIDDEN;
   }
}
```

Thanks

### CODE REVIEW

**Comment by boynton** [comment]
I would prefer to not introduce the '-' in a "name", the definition of a name specifically avoids this so that names can be used as identifiers in target languages.

Better to use the terms "consumes" and "produces", also because the term "accepts" already means something in HTTP.

So, I'd prefer to see this:

```
resource String POST "/CustomContentType" {
   String body

   consumes application/xml, application/json  // some comment here
   produces application/json, application/xml, text/plain;

   expected OK;
   exceptions {
       ResourceError INTERNAL_SERVER_ERROR;
       ResourceError BAD_REQUEST;
       ResourceError UNAUTHORIZED;
       ResourceError FORBIDDEN;
   }
}
```

without changing the parser to allow dashes in a "name" type of token.

**Comment by boynton** [comment]
👍

**Comment by boynton** [comment]
I'll follow up with the ardielle-common/rdl.rdl change and re-codegen for ardielle-java

**Comment by ben-tsai** [comment]
Thanks.  I might be able to help with ardielle-common/rdl.rdl part.

**Comment by ben-tsai** [comment]
https://github.com/ardielle/ardielle-common/pull/3
https://github.com/ardielle/ardielle-java/pull/3

**Pull request merged**
