### PR TITLE
Allow user to optional define alias for resources.

### PR DESCRIPTION
**Pull request by ben-tsai**
This PR enables the definition of an optional resource alias at the end of the endpoint definition (the idea is similar to the typedef definition of structs in C).  

It looks something like this:

```
resource MpNullResult DELETE "/toses" {
    authenticate;

    expected NO_CONTENT;
    exceptions {
        ResourceError INTERNAL_SERVER_ERROR; 
        ResourceError BAD_REQUEST;           
        ResourceError UNAUTHORIZED;       
        ResourceError FORBIDDEN;
    }
} deleteTos;
```

Thanks

### CODE REVIEW

**Comment by boynton** [comment]
I think that syntax is an anonomoly, there already is a syntax for resource attributes, would make sense to put it there (and just call it "name"):

```
resource MpNullResult DELETE "/toses" (name="deleteTos") {
    authenticate;

    expected NO_CONTENT;
    exceptions {
        ResourceError INTERNAL_SERVER_ERROR; 
        ResourceError BAD_REQUEST;           
        ResourceError UNAUTHORIZED;       
        ResourceError FORBIDDEN;
    }
}
```

This does show that the railroad diagrams in the spec for the syntax of a resource definition are out of date. That should get fixed regardless of this issue.

**Comment by ben-tsai** [comment]
Hi, I've changed the key name to **_name_** and use attributes as suggested.  But instead of using string literal I think we should use Identifier for stricter naming and language compatibility:

```
resource MpNullResult DELETE "/toses" (name=deleteTos) {
    authenticate;

    expected NO_CONTENT;
    exceptions {
        ResourceError INTERNAL_SERVER_ERROR; 
        ResourceError BAD_REQUEST;           
        ResourceError UNAUTHORIZED;       
        ResourceError FORBIDDEN;
    }
}
```

Thanks

**Comment by ben-tsai** [comment]
Hi @boynton, review please.  Thanks

**Comment by boynton** [comment]
👍

**Pull request merged**
