### PR TITLE
support status code 422 UNPROCESSABLE_ENTITY

### PR DESCRIPTION
**Pull request by joejoe321321**
Hi, we'd like to generate markdown from rdl with 422 status code. Could you help us?

### CODE REVIEW

**Comment by boynton** [comment]
I don't mind adding the symbols, but you can always just declare the expected or exception status as "422" and it passes through.

**Comment by joejoe321321** [comment]
Oh, you're right. We just want to add a readable symbol for our user. We will suggest them to add status code directly.
We'll be happier if you can add it, but we can wait.  :D
Thank you.

**Comment by joejoe321321** [comment]
Hmm, I cannot generate 422 status code by directly add 422 into exceptions.
What I did is trying to parse the following content with $ rdl generate json sample.rdl

>  ...
>  exceptions {
>        ResourceError INTERNAL_SERVER_ERROR;
>        ResourceError BAD_REQUEST;
>        ResourceError UNAUTHORIZED;
>        ResourceError FORBIDDEN;
>        ResourceError 422;
>    }
>  ...

But rdl throw error message:
*** Error(sample.rdl:22): expected 'symbol', found '422'

Did I misunderstand anything?

**Comment by boynton** [comment]
Oh, you're right :-) The parser expects an "identifier", which must start with an alpha char, not a number.I'll merge your change for now.

**Comment by joejoe321321** [comment]
Thank you:)

**Pull request merged**
